import RARITY from '../model/pokemon-rarity';

export const pokemonListComplete = [
  {
    name: 'Bulbasaur', // Name to be displayed
    key: 'bulbasaur', // Name as in the list bellow
    number: 1,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Ivysaur',
    key: 'ivysaur',
    number: 2,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Venusaur',
    key: 'venusaur',
    number: 3,
    rarity: RARITY.RARE,
  },
  {
    name: 'Charmander',
    key: 'charmander',
    number: 4,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Charmeleon',
    key: 'charmeleon',
    number: 5,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Charizard',
    key: 'charizard',
    number: 6,
    rarity: RARITY.RARE,
  },
  {
    name: 'Squirtle',
    key: 'squirtle',
    number: 7,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Wartortle',
    key: 'wartortle',
    number: 8,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Blastoise',
    key: 'blastoise',
    number: 9,
    rarity: RARITY.RARE,
  },
  {
    name: 'Caterpie',
    key: 'caterpie',
    number: 10,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Metapod',
    key: 'metapod',
    number: 11,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Butterfree',
    key: 'butterfree',
    number: 12,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Weedle',
    key: 'weedle',
    number: 13,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Kakuna',
    key: 'kakuna',
    number: 14,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Beedrill',
    key: 'beedrill',
    number: 15,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Pidgey',
    key: 'pidgey',
    number: 16,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Pidgeotto',
    key: 'pidgeotto',
    number: 17,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Pidgeot',
    key: 'pidgeot',
    number: 18,
    rarity: RARITY.RARE,
  },
  {
    name: 'Rattata',
    key: 'rattata',
    number: 19,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Raticate',
    key: 'raticate',
    number: 20,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Spearow',
    key: 'spearow',
    number: 21,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Fearow',
    key: 'fearow',
    number: 22,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Ekans',
    key: 'ekans',
    number: 23,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Arbok',
    key: 'arbok',
    number: 24,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Pikachu',
    key: 'pikachu',
    number: 25,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Raichu',
    key: 'raichu',
    number: 26,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Sandshrew',
    key: 'sandshrew',
    number: 27,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Sandslash',
    key: 'sandslash',
    number: 28,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Nidoran ♀',
    key: 'nidoran-f',
    number: 29,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Nidorina',
    key: 'nidorina',
    number: 30,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Nidoqueen',
    key: 'nidoqueen',
    number: 31,
    rarity: RARITY.RARE,
  },
  {
    name: 'Nidoran ♂',
    key: 'nidoran-m',
    number: 32,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Nidorino',
    key: 'nidorino',
    number: 33,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Nidoking',
    key: 'nidoking',
    number: 34,
    rarity: RARITY.RARE,
  },
  {
    name: 'Clefairy',
    key: 'clefairy',
    number: 35,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Clefable',
    key: 'clefable',
    number: 36,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Vulpix',
    key: 'vulpix',
    number: 37,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Ninetales',
    key: 'ninetales',
    number: 38,
    rarity: RARITY.RARE,
  },
  {
    name: 'Jigglypuff',
    key: 'jigglypuff',
    number: 39,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Wigglytuff',
    key: 'wigglytuff',
    number: 40,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Zubat',
    key: 'zubat',
    number: 41,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Golbat',
    key: 'golbat',
    number: 42,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Oddish',
    key: 'oddish',
    number: 43,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Gloom',
    key: 'gloom',
    number: 44,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Vileplume',
    key: 'vileplume',
    number: 45,
    rarity: RARITY.RARE,
  },
  {
    name: 'Paras',
    key: 'paras',
    number: 46,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Parasect',
    key: 'parasect',
    number: 47,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Venonat',
    key: 'venonat',
    number: 48,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Venomoth',
    key: 'venomoth',
    number: 49,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Diglett',
    key: 'diglett',
    number: 50,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Dugtrio',
    key: 'dugtrio',
    number: 51,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Meowth',
    key: 'meowth',
    number: 52,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Persian',
    key: 'persian',
    number: 53,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Psyduck',
    key: 'psyduck',
    number: 54,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Golduck',
    key: 'golduck',
    number: 55,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Mankey',
    key: 'mankey',
    number: 56,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Primeape',
    key: 'primeape',
    number: 57,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Growlithe',
    key: 'growlithe',
    number: 58,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Arcanine',
    key: 'arcanine',
    number: 59,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Poliwag',
    key: 'poliwag',
    number: 60,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Poliwhirl',
    key: 'poliwhirl',
    number: 61,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Poliwrath',
    key: 'poliwrath',
    number: 62,
    rarity: RARITY.RARE,
  },
  {
    name: 'Abra',
    key: 'abra',
    number: 63,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Kadabra',
    key: 'kadabra',
    number: 64,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Alakazam',
    key: 'alakazam',
    number: 65,
    rarity: RARITY.RARE,
  },
  {
    name: 'Machop',
    key: 'machop',
    number: 66,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Machoke',
    key: 'machoke',
    number: 67,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Machamp',
    key: 'machamp',
    number: 68,
    rarity: RARITY.RARE,
  },
  {
    name: 'Bellsprout',
    key: 'bellsprout',
    number: 69,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Weepinbell',
    key: 'weepinbell',
    number: 70,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Victreebel',
    key: 'victreebel',
    number: 71,
    rarity: RARITY.RARE,
  },
  {
    name: 'Tentacool',
    key: 'tentacool',
    number: 72,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Tentacruel',
    key: 'tentacruel',
    number: 73,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Geodude',
    key: 'geodude',
    number: 74,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Graveler',
    key: 'graveler',
    number: 75,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Golem',
    key: 'golem',
    number: 76,
    rarity: RARITY.RARE,
  },
  {
    name: 'Ponyta',
    key: 'ponyta',
    number: 77,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Rapidash',
    key: 'rapidash',
    number: 78,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Slowpoke',
    key: 'slowpoke',
    number: 79,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Slowbro',
    key: 'slowbro',
    number: 80,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Magnemite',
    key: 'magnemite',
    number: 81,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Magneton',
    key: 'magneton',
    number: 82,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: "Farfetch'd",
    key: 'farfetchd',
    number: 83,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Doduo',
    key: 'doduo',
    number: 84,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Dodrio',
    key: 'dodrio',
    number: 85,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Seel',
    key: 'seel',
    number: 86,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Dewgong',
    key: 'dewgong',
    number: 87,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Grimer',
    key: 'grimer',
    number: 88,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Muk',
    key: 'muk',
    number: 89,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Shellder',
    key: 'shellder',
    number: 90,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Cloyster',
    key: 'cloyster',
    number: 91,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Gastly',
    key: 'gastly',
    number: 92,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Haunter',
    key: 'haunter',
    number: 93,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Gengar',
    key: 'gengar',
    number: 94,
    rarity: RARITY.RARE,
  },
  {
    name: 'Onix',
    key: 'onix',
    number: 95,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Drowzee',
    key: 'drowzee',
    number: 96,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Hypno',
    key: 'hypno',
    number: 97,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Krabby',
    key: 'krabby',
    number: 98,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Kingler',
    key: 'kingler',
    number: 99,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Voltorb',
    key: 'voltorb',
    number: 100,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Electrode',
    key: 'electrode',
    number: 101,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Exeggcute',
    key: 'exeggcute',
    number: 102,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Exeggutor',
    key: 'exeggutor',
    number: 103,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Cubone',
    key: 'cubone',
    number: 104,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Marowak',
    key: 'marowak',
    number: 105,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Hitmonlee',
    key: 'hitmonlee',
    number: 106,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Hitmonchan',
    key: 'hitmonchan',
    number: 107,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Lickitung',
    key: 'lickitung',
    number: 108,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Koffing',
    key: 'koffing',
    number: 109,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Weezing',
    key: 'weezing',
    number: 110,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Rhyhorn',
    key: 'rhyhorn',
    number: 111,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Rhydon',
    key: 'rhydon',
    number: 112,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Chansey',
    key: 'chansey',
    number: 113,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Tangela',
    key: 'tangela',
    number: 114,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Kangaskhan',
    key: 'kangaskhan',
    number: 115,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Horsea',
    key: 'horsea',
    number: 116,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Seadra',
    key: 'seadra',
    number: 117,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Goldeen',
    key: 'goldeen',
    number: 118,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Seaking',
    key: 'seaking',
    number: 119,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Staryu',
    key: 'staryu',
    number: 120,
    rarity: RARITY.COMMON,
  },
  {
    name: 'Starmie',
    key: 'starmie',
    number: 121,
    rarity: RARITY.UNCOMMON,
  },
  {
    name: 'Mew',
    key: 'mew',
    number: 151,
    rarity: RARITY.LEGENDARY,
  },
];

export const pokemonList = [
  'bulbasaur',
  'ivysaur',
  'venusaur',
  'charmander',
  'charmeleon',
  'charizard',
  'squirtle',
  'wartortle',
  'blastoise',
  'caterpie',
  'metapod',
  'butterfree',
  'weedle',
  'kakuna',
  'beedrill',
  'pidgey',
  'pidgeotto',
  'pidgeot',
  'rattata',
  'raticate',
  'spearow',
  'fearow',
  'ekans',
  'arbok',
  'pikachu',
  'raichu',
  'sandshrew',
  'sandslash',
  'nidoran-f',
  'nidorina',
  'nidoqueen',
  'nidoran-m',
  'nidorino',
  'nidoking',
  'clefairy',
  'clefable',
  'vulpix',
  'ninetales',
  'jigglypuff',
  'wigglytuff',
  'zubat',
  'golbat',
  'oddish',
  'gloom',
  'vileplume',
  'paras',
  'parasect',
  'venonat',
  'venomoth',
  'diglett',
  'dugtrio',
  'meowth',
  'persian',
  'psyduck',
  'golduck',
  'mankey',
  'primeape',
  'growlithe',
  'arcanine',
  'poliwag',
  'poliwhirl',
  'poliwrath',
  'abra',
  'kadabra',
  'alakazam',
  'machop',
  'machoke',
  'machamp',
  'bellsprout',
  'weepinbell',
  'victreebel',
  'tentacool',
  'tentacruel',
  'geodude',
  'graveler',
  'golem',
  'ponyta',
  'rapidash',
  'slowpoke',
  'slowbro',
  'magnemite',
  'magneton',
  'farfetchd',
  'doduo',
  'dodrio',
  'seel',
  'dewgong',
  'grimer',
  'muk',
  'shellder',
  'cloyster',
  'gastly',
  'haunter',
  'gengar',
  'onix',
  'drowzee',
  'hypno',
  'krabby',
  'kingler',
  'voltorb',
  'electrode',
  'exeggcute',
  'exeggutor',
  'cubone',
  'marowak',
  'hitmonlee',
  'hitmonchan',
  'lickitung',
  'koffing',
  'weezing',
  'rhyhorn',
  'rhydon',
  'chansey',
  'tangela',
  'kangaskhan',
  'horsea',
  'seadra',
  'goldeen',
  'seaking',
  'staryu',
  'starmie',
  'mr-mime',
  'scyther',
  'jynx',
  'electabuzz',
  'magmar',
  'pinsir',
  'tauros',
  'magikarp',
  'gyarados',
  'lapras',
  'ditto',
  'eevee',
  'vaporeon',
  'jolteon',
  'flareon',
  'porygon',
  'omanyte',
  'omastar',
  'kabuto',
  'kabutops',
  'aerodactyl',
  'snorlax',
  'articuno',
  'zapdos',
  'moltres',
  'dratini',
  'dragonair',
  'dragonite',
  'mewtwo',
  'mew',
];
